const fs = require('fs');
const originalLines = fs.readFileSync('client/src/pages/TopicDetail.tsx', 'utf-8').split('\n');
const beforeActionGen = originalLines.slice(0, 135).join('\n');
const afterActionGen = originalLines.slice(1448, 1474).join('\n');
const afterPanel = originalLines.slice(1769).join('\n');
const imports = `import { useActionGenerator, Step } from './topic-detail/useActionGenerator';\nimport { InteractionPanel } from './topic-detail/InteractionPanel';\n`;
const modifiedBefore = beforeActionGen.replace(`import Visualizer from './topic-detail/Visualizer';`, `import Visualizer from './topic-detail/Visualizer';\n` + imports);
let finalBefore = modifiedBefore.replace(/interface Step \{[\s\S]*?\}/, '');
const newTopicDetail = finalBefore + '\n  const { generateStepsForAction, stopPlayback } = useActionGenerator(liveData, setLiveData, setSteps, setCurrentStepIdx, setIsPlaying);\n\n' + afterActionGen + '\n  const renderInteractionPanel = () => {\n    return <InteractionPanel\n      topic={topic}\n      interVal={interVal} setInterVal={setInterVal}\n      interIdx={interIdx} setInterIdx={setInterIdx}\n      generateStepsForAction={generateStepsForAction}\n      setLiveData={setLiveData}\n      setSteps={setSteps}\n      setCurrentStepIdx={setCurrentStepIdx}\n      selectedStartNode={selectedStartNode} setSelectedStartNode={setSelectedStartNode}\n      playbackSpeed={playbackSpeed} setPlaybackSpeed={setPlaybackSpeed}\n    />;\n  };\n' + afterPanel;
fs.writeFileSync('client/src/pages/TopicDetail.tsx', newTopicDetail);
console.log('Fixed!');
