using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Infrastructure.Persistence.Data;
// <auto-generated />

#nullable disable

namespace Infrastructure.Persistence.Data.Migrations
{
[DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511043159_AddRowVersionColumns")]
    partial class AddRowVersionColumns
    {
/// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
modelBuilder.Entity("Domain.Models.BattleModule.BattleParticipant", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<Guid>("BattleSessionId")
                        .HasColumnType("uniqueidentifier");
b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");
b.Property<int>("RatingAfter")
                        .HasColumnType("int");
b.Property<int>("RatingBefore")
                        .HasColumnType("int");
b.Property<int>("RatingDelta")
                        .HasColumnType("int");
b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
b.Property<int>("SolvedCount")
                        .HasColumnType("int");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.HasKey("Id");
b.HasIndex("BattleSessionId");
b.HasIndex("UserId");
b.ToTable("BattleParticipants");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleProblem", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<Guid>("BattleSessionId")
                        .HasColumnType("uniqueidentifier");
b.Property<int>("Order")
                        .HasColumnType("int");
b.Property<int>("ProblemId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("BattleSessionId");
b.HasIndex("ProblemId");
b.ToTable("BattleProblems");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleSession", b =>
                {
b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");
b.Property<int>("Mode")
                        .HasColumnType("int");
b.Property<int>("ProblemsToWin")
                        .HasColumnType("int");
b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");
b.Property<int>("Status")
                        .HasColumnType("int");
b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int");
b.Property<string>("WinnerUserId")
                        .HasColumnType("nvarchar(450)");
b.HasKey("Id");
b.HasIndex("WinnerUserId");
b.ToTable("BattleSessions");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleSubmission", b =>
                {
b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
b.Property<int?>("BattleParticipantId")
                        .HasColumnType("int");
b.Property<int>("BattleProblemId")
                        .HasColumnType("int");
b.Property<Guid>("BattleSessionId")
                        .HasColumnType("uniqueidentifier");
b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");
b.Property<int>("Language")
                        .HasColumnType("int");
b.Property<long?>("MemoryKb")
                        .HasColumnType("bigint");
b.Property<int>("PassedTestCases")
                        .HasColumnType("int");
b.Property<long?>("RuntimeMs")
                        .HasColumnType("bigint");
b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");
b.Property<int>("TotalTestCases")
                        .HasColumnType("int");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<int?>("Verdict")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("BattleParticipantId");
b.HasIndex("BattleProblemId");
b.HasIndex("BattleSessionId");
b.HasIndex("UserId");
b.ToTable("BattleSubmissions");
});
modelBuilder.Entity("Domain.Models.BattleModule.Friendship", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");
b.Property<int>("Status")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("AddresseeId");
b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();
b.ToTable("Friendships");
});
modelBuilder.Entity("Domain.Models.BattleModule.MatchmakingEntry", b =>
                {
b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
b.Property<int>("Mode")
                        .HasColumnType("int");
b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime2");
b.Property<int>("RankPoints")
                        .HasColumnType("int");
b.Property<Guid?>("ResultBattleSessionId")
                        .HasColumnType("uniqueidentifier");
b.Property<int>("Status")
                        .HasColumnType("int");
b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(max)");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.HasKey("Id");
b.HasIndex("UserId");
b.ToTable("MatchmakingEntries");
});
modelBuilder.Entity("Domain.Models.BattleModule.PlayerStats", b =>
                {
b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");
b.Property<int>("BestStreak")
                        .HasColumnType("int");
b.Property<int>("CurrentStreak")
                        .HasColumnType("int");
b.Property<int>("DrawCount")
                        .HasColumnType("int");
b.Property<int>("Level")
                        .HasColumnType("int");
b.Property<int>("LossCount")
                        .HasColumnType("int");
b.Property<int>("PreferredLanguage")
                        .HasColumnType("int");
b.Property<int>("RankPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000);
b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
b.Property<int>("WinCount")
                        .HasColumnType("int");
b.HasKey("UserId");
b.HasIndex("RankPoints")
                        .IsDescending()
                        .HasDatabaseName("IX_PlayerStats_RankPoints");
b.ToTable("PlayerStats");
});
modelBuilder.Entity("Domain.Models.IdentityModule.ApplicationUser", b =>
                {
b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");
b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");
b.Property<bool>("IsActive")
                        .HasColumnType("bit");
b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");
b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");
b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");
b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");
b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");
b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");
b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");
b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");
b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.HasKey("Id");
b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");
b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");
b.ToTable("Users", (string)null);
});
modelBuilder.Entity("Domain.Models.IdentityModule.RefreshToken", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");
b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);
b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.HasKey("Id");
b.HasIndex("UserId");
b.ToTable("RefreshTokens");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.LearningPath", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<int>("Order")
                        .HasColumnType("int");
b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.HasKey("Id");
b.ToTable("LearningPaths");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.LearningPathLevel", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<int>("LearningPathId")
                        .HasColumnType("int");
b.Property<int>("Order")
                        .HasColumnType("int");
b.Property<int?>("ProblemId")
                        .HasColumnType("int");
b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<int?>("TopicId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("LearningPathId");
b.HasIndex("ProblemId");
b.HasIndex("TopicId");
b.ToTable("LearningPathLevels");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.UserLearningPathProgress", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");
b.Property<int>("CurrentLevelOrder")
                        .HasColumnType("int");
b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");
b.Property<int>("LearningPathId")
                        .HasColumnType("int");
b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.HasKey("Id");
b.HasIndex("LearningPathId");
b.ToTable("UserLearningPathProgresses");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Problem", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<int>("MemoryLimitKb")
                        .HasColumnType("int");
b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
b.Property<int>("TimeLimitMs")
                        .HasColumnType("int");
b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
b.Property<int>("TopicId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("Slug")
                        .IsUnique();
b.HasIndex("TopicId", "Difficulty");
b.ToTable("Problems");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Submission", b =>
                {
b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<long?>("MemoryKb")
                        .HasColumnType("bigint");
b.Property<int>("ProblemId")
                        .HasColumnType("int");
b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");
b.Property<long?>("RuntimeMs")
                        .HasColumnType("bigint");
b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<string>("Verdict")
                        .HasColumnType("nvarchar(max)");
b.HasKey("Id");
b.HasIndex("ProblemId");
b.HasIndex("Status");
b.HasIndex("UserId", "SubmittedAt");
b.HasIndex("UserId", "ProblemId", "SubmittedAt");
b.ToTable("Submissions");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.SubmissionTestResult", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("ActualOutput")
                        .HasColumnType("nvarchar(max)");
b.Property<long>("MemoryKb")
                        .HasColumnType("bigint");
b.Property<long>("RuntimeMs")
                        .HasColumnType("bigint");
b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");
b.Property<int>("TestCaseId")
                        .HasColumnType("int");
b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.HasKey("Id");
b.HasIndex("SubmissionId");
b.HasIndex("TestCaseId");
b.ToTable("SubmissionTestResults");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.TestCase", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);
b.Property<int>("ProblemId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("ProblemId");
b.ToTable("TestCases");
});
modelBuilder.Entity("Domain.Models.TopicModule.Category", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
b.HasKey("Id");
b.ToTable("Categories");
});
modelBuilder.Entity("Domain.Models.TopicModule.Topic", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<int>("CategoryId")
                        .HasColumnType("int");
b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
b.HasKey("Id");
b.HasIndex("CategoryId");
b.HasIndex("Slug")
                        .IsUnique();
b.ToTable("Topics");
});
modelBuilder.Entity("Domain.Models.TopicModule.TopicCodeImplementation", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.Property<string>("StepsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");
b.Property<int>("TopicId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("TopicId", "Language")
                        .IsUnique();
b.ToTable("TopicCodeImplementations");
});
modelBuilder.Entity("Domain.Models.TopicModule.TopicComplexity", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
b.Property<string>("SpaceComplexity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
b.Property<string>("TimeComplexity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
b.Property<int>("TopicId")
                        .HasColumnType("int");
b.HasKey("Id");
b.HasIndex("TopicId");
b.ToTable("TopicComplexities");
});
modelBuilder.Entity("Domain.Models.TopicModule.UserTopicProgress", b =>
                {
b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");
b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");
b.Property<int>("TopicId")
                        .HasColumnType("int");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.HasKey("Id");
b.HasIndex("TopicId");
b.HasIndex("UserId", "TopicId")
                        .IsUnique();
b.ToTable("UserTopicProgresses");
});
modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");
b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");
b.HasKey("Id");
b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");
b.ToTable("Roles", (string)null);
});
modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");
b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");
b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");
b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");
b.HasKey("LoginProvider", "ProviderKey");
b.HasIndex("UserId");
b.ToTable("AspNetUserLogins", (string)null);
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleParticipant", b =>
                {
b.HasOne("Domain.Models.BattleModule.BattleSession", "BattleSession")
                        .WithMany("Participants")
                        .HasForeignKey("BattleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.Navigation("BattleSession");
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleProblem", b =>
                {
b.HasOne("Domain.Models.BattleModule.BattleSession", "BattleSession")
                        .WithMany("Problems")
                        .HasForeignKey("BattleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.ProblemsModule.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.Navigation("BattleSession");
b.Navigation("Problem");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleSession", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerUserId");
b.Navigation("Winner");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleSubmission", b =>
                {
b.HasOne("Domain.Models.BattleModule.BattleParticipant", null)
                        .WithMany("Submissions")
                        .HasForeignKey("BattleParticipantId");
b.HasOne("Domain.Models.BattleModule.BattleProblem", "BattleProblem")
                        .WithMany()
                        .HasForeignKey("BattleProblemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.HasOne("Domain.Models.BattleModule.BattleSession", "BattleSession")
                        .WithMany()
                        .HasForeignKey("BattleSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.Navigation("BattleProblem");
b.Navigation("BattleSession");
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.BattleModule.Friendship", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.Navigation("Addressee");
b.Navigation("Requester");
});
modelBuilder.Entity("Domain.Models.BattleModule.MatchmakingEntry", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.BattleModule.PlayerStats", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Models.BattleModule.PlayerStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.IdentityModule.RefreshToken", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.LearningPathLevel", b =>
                {
b.HasOne("Domain.Models.LearningPathModule.LearningPath", "LearningPath")
                        .WithMany("Levels")
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.ProblemsModule.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId");
b.HasOne("Domain.Models.TopicModule.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
b.Navigation("LearningPath");
b.Navigation("Problem");
b.Navigation("Topic");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.UserLearningPathProgress", b =>
                {
b.HasOne("Domain.Models.LearningPathModule.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("LearningPath");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Problem", b =>
                {
b.HasOne("Domain.Models.TopicModule.Topic", "Topic")
                        .WithMany("Problems")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("Topic");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Submission", b =>
                {
b.HasOne("Domain.Models.ProblemsModule.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
b.Navigation("Problem");
b.Navigation("User");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.SubmissionTestResult", b =>
                {
b.HasOne("Domain.Models.ProblemsModule.Submission", "Submission")
                        .WithMany("SubmissionTestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.ProblemsModule.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
b.Navigation("Submission");
b.Navigation("TestCase");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.TestCase", b =>
                {
b.HasOne("Domain.Models.ProblemsModule.Problem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("Problem");
});
modelBuilder.Entity("Domain.Models.TopicModule.Topic", b =>
                {
b.HasOne("Domain.Models.TopicModule.Category", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
b.Navigation("Category");
});
modelBuilder.Entity("Domain.Models.TopicModule.TopicCodeImplementation", b =>
                {
b.HasOne("Domain.Models.TopicModule.Topic", "Topic")
                        .WithMany("CodeImplementations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("Topic");
});
modelBuilder.Entity("Domain.Models.TopicModule.TopicComplexity", b =>
                {
b.HasOne("Domain.Models.TopicModule.Topic", "Topic")
                        .WithMany("Complexities")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.Navigation("Topic");
});
modelBuilder.Entity("Domain.Models.TopicModule.UserTopicProgress", b =>
                {
b.HasOne("Domain.Models.TopicModule.Topic", "Topic")
                        .WithMany("UserProgresses")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
b.Navigation("Topic");
b.Navigation("User");
});
modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
b.HasOne("Domain.Models.IdentityModule.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleParticipant", b =>
                {
b.Navigation("Submissions");
});
modelBuilder.Entity("Domain.Models.BattleModule.BattleSession", b =>
                {
b.Navigation("Participants");
b.Navigation("Problems");
});
modelBuilder.Entity("Domain.Models.IdentityModule.ApplicationUser", b =>
                {
b.Navigation("RefreshTokens");
b.Navigation("UserProgresses");
});
modelBuilder.Entity("Domain.Models.LearningPathModule.LearningPath", b =>
                {
b.Navigation("Levels");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Problem", b =>
                {
b.Navigation("Submissions");
b.Navigation("TestCases");
});
modelBuilder.Entity("Domain.Models.ProblemsModule.Submission", b =>
                {
b.Navigation("SubmissionTestResults");
});
modelBuilder.Entity("Domain.Models.TopicModule.Category", b =>
                {
b.Navigation("Topics");
});
modelBuilder.Entity("Domain.Models.TopicModule.Topic", b =>
                {
b.Navigation("CodeImplementations");
b.Navigation("Complexities");
b.Navigation("Problems");
b.Navigation("UserProgresses");
});
#pragma warning restore 612, 618
        }
}
}

